const CHAT_ENUMS = {
  PRIVATE: "PRIVATE",
  GROUP: "GROUP",
};

const LAND_ENUMS = {
  RENTAL: "RENTAL",
  FOOD: "FOOD",
  FUEL: "FUEL",
};

const GAME_TYPE_ENUMS = {
  CHECKERS: "CHECKERS",
  EIGHTBALLPOOL: "EIGHTBALLPOOL",
  CHESS: "CHESS",
  DART: "DART",
  BASKETBALL: "BASKETBALL",
  VOLLEYBALL: "VOLLEYBALL",
  SOCCER: "SOCCER",
  PAINTBALL: "PAINTBALL",
};

export { CHAT_ENUMS, LAND_ENUMS, GAME_TYPE_ENUMS };
